package ch.shopyfly.shopyfly.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import java.util.Optional;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name, @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @PostMapping(path="/register")
    public @ResponseBody String registerUser (@RequestParam String name, @RequestParam String email) {
        if(userRepository.findByName(name).isPresent()){
            return "Benutzername bereits vorhanden.";
        }
        User newUser = new User();
        newUser.setName(name);
        newUser.setEmail(email);
        userRepository.save(newUser);
        return "Benutzer erfolgreich registriert.";
    }

    @GetMapping(path="/register")
    @ResponseBody
    public String showRegistrationForm() {
        return "<!DOCTYPE html>" +
                "<html>" +
                "<head><title>Registrierung</title></head>" +
                "<body>" +
                "<form action='/demo/register' method='post'>" +
                "Name: <input type='text' name='name'><br>" +
                "E-Mail: <input type='text' name='email'><br>" +
                "<input type='submit' value='Registrieren'>" +
                "</form>" +
                "</body>" +
                "</html>";
    }

    @GetMapping(path="/findByName")
    public @ResponseBody String findByName(@RequestParam String name) {
        Optional<User> optionalUser = userRepository.findByName(name);
        if (optionalUser.isPresent()) {
            return optionalUser.get().getName() + ", " + optionalUser.get().getEmail();
        } else {
            return "User not found!";
        }
    }
}
